import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link } from "wouter";
import { ArrowRight, BarChart3, Bot, ChevronRight, Newspaper, Trophy, Users } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useDebates, useLeaderboard, useMatches, useRecentMatches, useUpcomingFixtures } from "../hooks/useData";
import { fetchTodaysFixtures } from "../lib/football-api";
import { fetchFootballNews, fetchPartnerArticles, timeAgo, type NewsArticle } from "../lib/news-api";
import { getHomepageMode, selectFeaturedMatch, type HomepageMatch } from "../lib/home-season";
import SEO from "../components/SEO";
import TeamLogo from "../components/TeamLogo";
import { supabase } from "../lib/supabase";

const DEFAULT_IMAGE = "/images/hero_player_celebration.png";
const ANALYST_IMAGE = "/images/analyst_chalkboard.png";
const FANS_IMAGE = "/images/kenyan_fans.png";
const FOOTBALL_TERMS = ["football", "soccer", "premier league", "champions league", "epl", "transfer", "fixture", "match", "league", "cup", "africa", "caf", "afcon", "kenya", "harambee", "fkf", "gor mahia", "afc leopards", "tusker", "goal"];
const NON_FOOTBALL_TERMS = ["president", "senate", "congress", "government", "politics", "election", "court", "war", "tariff", "economy", "minister"];

function copyOf(a: Pick<NewsArticle, "title" | "description" | "source">) { return `${a.title} ${a.description || ""} ${a.source || ""}`.toLowerCase(); }
function isFootball(a: Pick<NewsArticle, "title" | "description" | "source">) { const value = copyOf(a); return FOOTBALL_TERMS.some((term) => value.includes(term)) && !NON_FOOTBALL_TERMS.some((term) => value.includes(term)); }
function linkFor(a: NewsArticle) { return a.isInternal ? `/news/${a.slug}` : a.link; }
function keyFor(a: NewsArticle) { return a.title.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
function category(a: NewsArticle, fallback = "Mtaa Daily") { const value = copyOf(a); if (a.isOfficial) return "Official FKF"; if (a.desk === "kenya" || /kenya|fkf|harambee|gor mahia|afc leopards|tusker/.test(value)) return "Kenya"; if (/africa|caf|afcon|east africa/.test(value)) return "Africa"; if (/analysis|opinion|tactic|breakdown|preview/.test(value)) return "Analysis"; if (/transfer/.test(value)) return "Transfers"; if (/premier league|arsenal|chelsea|liverpool|manchester|spurs/.test(value)) return "Premier League"; return fallback; }
function short(name: string) { return String(name || "").replace(/\s+(FC|SC|AFC|City|United|Town|Rovers|Athletic|Stars?)$/i, "").trim(); }
function kickoff(match?: HomepageMatch) { return match?.time || (match?.kickoffAt ? new Date(match.kickoffAt).toLocaleTimeString("en-KE", { hour: "numeric", minute: "2-digit", hour12: true, timeZone: "Africa/Nairobi" }) : "TBC"); }
function dedupe(list: NewsArticle[]) { const map = new Map<string, NewsArticle>(); for (const a of list) { const key = keyFor(a); const old = map.get(key); if (!old || (!old.isInternal && a.isInternal)) map.set(key, a); } return [...map.values()].sort((a, b) => +new Date(b.pubDate) - +new Date(a.pubDate)); }

function ArticleAnchor({ article, className, children }: { article: NewsArticle; className: string; children: ReactNode }) {
  return article.isInternal ? <Link href={linkFor(article)} className={className}>{children}</Link> : <a href={linkFor(article)} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>;
}
function Heading({ title, href, action = "View all" }: { title: string; href: string; action?: string }) {
  return <div className="flex h-9 items-center justify-between border-b border-white/10 px-3"><h2 className="text-[10px] font-black uppercase tracking-[.16em] text-[#ef3038]">{title}</h2><Link href={href} className="flex items-center gap-1 text-[9px] font-bold text-white/45 hover:text-white">{action}<ChevronRight className="h-3 w-3" /></Link></div>;
}
function RailStory({ article }: { article: NewsArticle }) {
  return <ArticleAnchor article={article} className="group grid min-h-0 flex-1 grid-cols-[42%_1fr] overflow-hidden bg-[#111]"><img src={article.thumbnail || DEFAULT_IMAGE} alt="" className="h-full min-h-[96px] w-full object-cover transition duration-500 group-hover:scale-[1.03]" onError={(e) => { e.currentTarget.src = DEFAULT_IMAGE; }} /><div className="flex min-w-0 flex-col justify-center px-4 py-3"><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#ef3038]">{category(article, article.source)}</p><h3 className="mt-1.5 line-clamp-3 text-[15px] font-extrabold leading-[1.08] group-hover:text-[#f5ca55]">{article.title}</h3><p className="mt-2 text-[9px] text-white/45">{timeAgo(article.pubDate)}</p></div></ArticleAnchor>;
}
function FeatureRail({ icon, label, title, href }: { icon: ReactNode; label: string; title: string; href: string }) {
  return <Link href={href} className="group grid min-h-[96px] flex-1 grid-cols-[42%_1fr] overflow-hidden bg-[#111]"><div className="flex items-center justify-center bg-[#151515] text-[#f5ca55]">{icon}</div><div className="flex flex-col justify-center px-4 py-3"><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#ef3038]">{label}</p><h3 className="mt-1.5 text-[15px] font-extrabold leading-[1.08] group-hover:text-[#f5ca55]">{title}</h3><p className="mt-2 text-[9px] text-white/45">Open desk</p></div></Link>;
}
function StoryDesk({ title, href, feature, supporting, fallback }: { title: string; href: string; feature?: NewsArticle; supporting: NewsArticle[]; fallback: { title: string; copy: string; href: string; image: string } }) {
  return <section className="min-w-0 bg-[#0c0c0c] ring-1 ring-white/10"><Heading title={title} href={href} />{feature ? <ArticleAnchor article={feature} className="group block"><div className="relative aspect-[16/8.3] overflow-hidden bg-[#121212]"><img src={feature.thumbnail || DEFAULT_IMAGE} alt={feature.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" loading="lazy" onError={(e) => { e.currentTarget.src = DEFAULT_IMAGE; }} /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/5 to-transparent" /></div><div className="px-3 pb-2.5 pt-2"><h3 className="line-clamp-2 text-[15px] font-extrabold leading-[1.08] group-hover:text-[#f5ca55]">{feature.title}</h3>{feature.description && <p className="mt-1 line-clamp-2 text-[11px] leading-[1.45] text-white/55">{feature.description}</p>}<p className="mt-1.5 text-[9px] text-white/35">{timeAgo(feature.pubDate)}</p></div></ArticleAnchor> : <Link href={fallback.href} className="group block"><div className="relative aspect-[16/8.3] overflow-hidden"><img src={fallback.image} alt="" className="h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-[1.03]" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent" /></div><div className="px-3 pb-3 pt-2"><h3 className="text-[15px] font-extrabold leading-tight group-hover:text-[#f5ca55]">{fallback.title}</h3><p className="mt-1 text-[11px] leading-[1.45] text-white/55">{fallback.copy}</p></div></Link>}{supporting.slice(0, 2).map((article) => <ArticleAnchor key={article.id || article.link} article={article} className="group grid grid-cols-[58px_1fr] gap-2.5 border-t border-white/10 p-2.5"><img src={article.thumbnail || DEFAULT_IMAGE} alt="" className="h-11 w-[58px] object-cover" loading="lazy" onError={(e) => { e.currentTarget.src = DEFAULT_IMAGE; }} /><div className="min-w-0"><h4 className="line-clamp-2 text-[11px] font-bold leading-[1.2] group-hover:text-[#f5ca55]">{article.title}</h4><p className="mt-1 text-[8px] text-white/35">{timeAgo(article.pubDate)}</p></div></ArticleAnchor>)}</section>;
}
function FooterColumn({ title, links }: { title: string; links: Array<[string, string]> }) { return <div><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/70">{title}</p><ul className="mt-3 space-y-2 text-[11px] text-white/48">{links.map(([label, href]) => <li key={label}><Link href={href} className="hover:text-white">{label}</Link></li>)}</ul></div>; }

export default function MagazineHomePage() {
  const { dbProfile } = useAuth();
  const { data: live = [] } = useMatches(); const { data: upcoming = [] } = useUpcomingFixtures(); const { data: recent = [] } = useRecentMatches();
  const { data: debates = [] } = useDebates(); const { data: leaderboard = [] } = useLeaderboard();
  const [today, setToday] = useState<HomepageMatch[]>([]); const [news, setNews] = useState<NewsArticle[]>([]); const [loading, setLoading] = useState(true); const [now, setNow] = useState(() => new Date());
  const [email, setEmail] = useState(""); const [formState, setFormState] = useState<"idle" | "submitting" | "success" | "error">("idle"); const [formError, setFormError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; fetchTodaysFixtures().then((items) => { if (!cancelled) setToday(items); }).catch(() => undefined); Promise.allSettled([fetchPartnerArticles(), fetchFootballNews()]).then(([partners, wire]) => { if (cancelled) return; setNews(dedupe([...(partners.status === "fulfilled" ? partners.value : []), ...(wire.status === "fulfilled" ? wire.value : [])])); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60000); return () => window.clearInterval(timer); }, []);
  const stories = useMemo(() => { const all = dedupe(news.filter((a) => a.isInternal || isFootball(a))); return [...all.filter((a) => a.isInternal), ...all.filter((a) => !a.isInternal)]; }, [news]); const external = useMemo(() => dedupe(news.filter((a) => !a.isInternal && isFootball(a))), [news]);
  const layout = useMemo(() => {
    const used = new Set<string>();
    const take = (terms: string[] = [], strict = false) => {
      const ranked = terms.length ? stories.filter((article) => terms.some((term) => copyOf(article).includes(term))) : stories;
      const candidates = strict && terms.length ? ranked : [...ranked, ...stories];
      const found = candidates.find((article) => !used.has(keyFor(article)));
      if (found) used.add(keyFor(found));
      return found;
    };
    const many = (count: number, terms: string[] = [], strict = false) =>
      Array.from({ length: count }, () => take(terms, strict)).filter(Boolean) as NewsArticle[];

    const lead = take();
    const rail = many(3);

    const kenyaTerms = ["harambee", "fkf", "kenya premier league", "kenyan premier league", "fkf premier league", "gor mahia", "afc leopards", "tusker", "shabana", "kakamega homeboyz", "bandari", "sofapaka", "kenya police", "east africa", "uganda premier league", "tanzania premier league"];
    const kenya = Array.from({ length: 3 }, () => {
      const found = stories.find((article) =>
        !used.has(keyFor(article)) &&
        !/world cup|wc26/.test(article.title.toLowerCase()) &&
        (article.desk === "kenya" || kenyaTerms.some((term) => copyOf(article).includes(term)))
      );
      if (found) used.add(keyFor(found));
      return found;
    }).filter(Boolean) as NewsArticle[];

    const epl = many(3, ["premier league", "arsenal", "chelsea", "liverpool", "manchester", "spurs"], true);
    const analysis = many(3, ["analysis", "opinion", "tactic", "breakdown", "preview", "explained"], true);
    while (analysis.length < 3) {
      const fallback = stories.find((article) => article.isInternal && !used.has(keyFor(article)));
      if (!fallback) break;
      used.add(keyFor(fallback));
      analysis.push(fallback);
    }

    return {
      lead,
      rail,
      kenya,
      epl,
      analysis,
      africa: many(1, ["africa", "caf", "afcon"], true),
    };
  }, [stories]);
  const featured = useMemo(() => selectFeaturedMatch({ liveMatches: live, upcomingFixtures: upcoming, recentMatches: recent, followedClub: dbProfile?.favorite_team || null }).match, [dbProfile?.favorite_team, live, upcoming, recent]);
  const liveLine = featured || live[0] || upcoming[0] || recent[0]; const fixtures = (today.length ? today : [...live, ...upcoming]).slice(0, 4); const scoreReady = !!liveLine && typeof liveLine.homeScore === "number" && typeof liveLine.awayScore === "number"; const mode = getHomepageMode({ now, liveMatches: live, todaysFixtures: today }); const badge = mode === "matchday" ? "MATCHDAY" : mode === "pre-season" ? "PRE-SEASON" : "FOOTBALL WEEK";
  const subscribe = async (event: FormEvent) => { event.preventDefault(); const clean = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(clean)) { setFormError("Enter a valid email address."); setFormState("error"); return; } setFormState("submitting"); setFormError(null); try { if (!supabase) throw new Error(); const { error } = await supabase.from("newsletter_subscribers").insert({ email: clean, source_page: "homepage", consent_timestamp: new Date().toISOString(), favorite_club: dbProfile?.favorite_team || null, created_at: new Date().toISOString() }); if (error) throw error; setEmail(""); setFormState("success"); } catch { setFormState("error"); setFormError("Subscription is temporarily unavailable."); } };
  const lead = layout.lead;
  return <main className="min-h-screen bg-[#050505] text-white"><SEO title="BALLMTAANI | Football. From where we stand." description="Premium Kenyan football news, live scores, analysis and fan community." path="/" canonicalUrl="/" image={lead?.thumbnail || DEFAULT_IMAGE} />
    <div className="mx-auto max-w-[1500px] px-3 py-3 sm:px-4 lg:py-4">
      <section id="mtaa-daily" className="grid gap-2 lg:grid-cols-[1.88fr_1fr]">
        {lead ? <ArticleAnchor article={lead} className="group relative min-h-[410px] overflow-hidden bg-[#101010] sm:min-h-[480px] lg:min-h-[520px]"><img src={lead.thumbnail || DEFAULT_IMAGE} alt={lead.title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]" onError={(e) => { e.currentTarget.src = DEFAULT_IMAGE; }} /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/45 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/10" /><div className="absolute inset-x-0 bottom-0 z-10 max-w-[680px] p-5 sm:p-8 lg:p-10"><div className="mb-4 flex items-center gap-3 text-[9px] font-black uppercase tracking-[.2em]"><span className="bg-[#bf1721] px-2.5 py-1">{category(lead, badge)}</span><span className="text-white/55">{timeAgo(lead.pubDate)}</span></div><h1 className="font-serif text-[2.15rem] font-black leading-[.97] tracking-[-.025em] sm:text-5xl lg:text-[3.5rem]">{lead.title}</h1>{lead.description && <p className="mt-4 line-clamp-2 max-w-[540px] text-sm leading-6 text-white/78 sm:text-base">{lead.description}</p>}<div className="mt-5 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[#ff3c44]">Read story <ArrowRight className="h-4 w-4" /></div></div></ArticleAnchor> : <Link href="/news" className="relative flex min-h-[410px] items-end overflow-hidden bg-[#101010] sm:min-h-[480px] lg:min-h-[520px]"><img src={DEFAULT_IMAGE} alt="Ball Mtaani football" className="absolute inset-0 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" /><div className="relative p-8"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#ef3038]">Mtaa Daily</p><h1 className="mt-3 max-w-xl font-serif text-5xl font-black leading-none">Football. From where we stand.</h1><p className="mt-4 text-sm text-white/65">Original Kenyan football reporting and analysis.</p></div></Link>}
        <aside className="flex min-h-[410px] flex-col gap-2 sm:min-h-[480px] lg:min-h-[520px]">{layout.rail.map((a) => <RailStory key={a.id || a.link} article={a} />)}{layout.rail.length < 3 && <FeatureRail icon={<Newspaper className="h-8 w-8" />} label="Mtaa Daily" title="News, analysis and the Kenyan angle" href="/news" />}{layout.rail.length < 2 && <FeatureRail icon={<Trophy className="h-8 w-8" />} label="Archive" title="World Cup 2026 stories and results" href="/world-cup-2026" />}{layout.rail.length < 1 && <FeatureRail icon={<Users className="h-8 w-8" />} label="Community" title="The debates Kenyan fans are having" href="/debates" />}<Link href="/news" className="flex h-9 flex-none items-center justify-center border border-white/15 text-[9px] font-black uppercase tracking-[.18em] text-[#f5ca55]">More top stories <ArrowRight className="ml-2 h-3 w-3" /></Link></aside>
      </section>
      <section className="mt-2 grid gap-2 lg:grid-cols-[1.05fr_.92fr_1.03fr]">
        <div className="bg-[#0d0d0d] ring-1 ring-white/10"><Heading title="Today in football" href="/matches" action="All fixtures" /><div className="divide-y divide-white/10 px-3">{fixtures.length ? fixtures.map((match) => <Link key={String(match.id)} href={`/match/${match.id}`} className="grid h-[42px] grid-cols-[42px_1fr_auto_1fr] items-center gap-2 text-[10px]"><span className="truncate uppercase text-white/35">{match.league || "Match"}</span><span className="truncate text-right font-bold text-white/80">{short(match.home)}</span><span className="font-black text-[#f5ca55]">{kickoff(match)}</span><span className="truncate font-bold text-white/80">{short(match.away)}</span></Link>) : <div className="grid h-[168px] place-items-center"><Link href="/matches" className="text-xs text-white/50 hover:text-white">Open today&apos;s fixtures</Link></div>}</div></div>
        <div className="bg-[#0d0d0d] ring-1 ring-white/10"><Heading title="Live match centre" href="/live-center" action="Live stats" />{liveLine ? <div className="flex h-[168px] flex-col justify-center px-4"><p className="text-center text-[9px] font-black uppercase tracking-[.18em] text-[#ef3038]">{liveLine.league || liveLine.status || "Match centre"}</p><div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="flex flex-col items-center gap-1.5"><TeamLogo logo={liveLine.homeLogo} initial={short(liveLine.home).slice(0,3).toUpperCase()} color={liveLine.homeColor || "#1f2937"} size="md" /><span className="line-clamp-1 text-xs font-bold">{short(liveLine.home)}</span></div><div className="text-center"><div className="text-4xl font-black">{scoreReady ? `${liveLine.homeScore}-${liveLine.awayScore}` : "VS"}</div><p className="mt-1 text-[9px] uppercase text-white/40">{kickoff(liveLine)}</p></div><div className="flex flex-col items-center gap-1.5"><TeamLogo logo={liveLine.awayLogo} initial={short(liveLine.away).slice(0,3).toUpperCase()} color={liveLine.awayColor || "#1f2937"} size="md" /><span className="line-clamp-1 text-xs font-bold">{short(liveLine.away)}</span></div></div></div> : <div className="grid h-[168px] place-items-center"><Link href="/live-center" className="text-xs text-white/50 hover:text-white"><BarChart3 className="mx-auto mb-2 h-5 w-5 text-[#ef3038]" />Open match centre</Link></div>}</div>
        <div className="relative min-h-[207px] overflow-hidden bg-[#0d0d0d] ring-1 ring-white/10"><Heading title="Mtaa intelligence" href="/mchambuzi-halisi" action="Ask Mchambuzi" /><div className="relative z-10 max-w-[72%] px-4 py-4"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#f5ca55]">Mchambuzi&apos;s read</p><p className="mt-2 text-[12px] leading-[1.55] text-white/72">{liveLine ? `${short(liveLine.home)} against ${short(liveLine.away)} is the match to read closely. Team news, tempo and game state will decide where the advantage shifts.` : "Team news, tempo and the detail everyone else misses."}</p><Link href="/mchambuzi-halisi" className="mt-4 inline-flex items-center gap-1.5 border border-[#f5ca55]/35 px-3 py-2 text-[9px] font-black uppercase text-[#f5ca55]"><Bot className="h-3.5 w-3.5" />Ask Mchambuzi</Link></div><img src={ANALYST_IMAGE} alt="" className="absolute bottom-0 right-0 h-[88%] w-[44%] object-cover object-left-top opacity-70" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-r from-[#0d0d0d] via-[#0d0d0d]/85 to-transparent" /></div>
      </section>
      <section className="mt-2 grid items-stretch gap-2 md:grid-cols-2 xl:grid-cols-4"><StoryDesk title="Kenya & East Africa" href="/news" feature={layout.kenya[0]} supporting={layout.kenya.slice(1)} fallback={{ title: "Kenyan football, every matchday", copy: "Follow fixtures, clubs and the stories shaping the local game.", href: "/leagues", image: FANS_IMAGE }} /><StoryDesk title="Premier League" href="/leagues" feature={layout.epl[0]} supporting={layout.epl.slice(1)} fallback={{ title: "The Premier League desk", copy: "Fixtures, tables, form and the latest coverage.", href: "/leagues", image: DEFAULT_IMAGE }} /><StoryDesk title="Analysis & Features" href="/articles" feature={layout.analysis[0]} supporting={layout.analysis.slice(1)} fallback={{ title: "Original football features", copy: "Reporting and perspective from the BallMtaani editorial desk.", href: "/articles", image: ANALYST_IMAGE }} /><section className="flex flex-col bg-[#080808] ring-1 ring-white/15"><div className="flex-1 p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ef3038]">The Mtaa Brief</p><h2 className="mt-3 font-serif text-[1.65rem] font-black leading-[1.05]">Football you need to know before the group chat starts.</h2><p className="mt-4 text-[11px] leading-5 text-white/55">Morning edition / Kenya / Africa / EPL / Transfers / Today&apos;s matches</p></div><form onSubmit={subscribe} className="border-t border-white/10 p-4"><label htmlFor="newsletter-email" className="sr-only">Email</label><input id="newsletter-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@email.com" className="h-11 w-full border border-white/15 bg-black px-3 text-xs outline-none placeholder:text-white/30 focus:border-[#ef3038]" /><button disabled={formState === "submitting"} className="mt-2 h-10 w-full bg-[#bf1721] text-[10px] font-black uppercase tracking-[.18em]">{formState === "submitting" ? "Joining..." : "Join free"}</button>{formError && <p className="mt-2 text-[10px] text-red-300">{formError}</p>}{formState === "success" && <p className="mt-2 text-[10px] text-emerald-300">You&apos;re in. The next edition is yours.</p>}</form></section></section>
      <section className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-4">
        <section id="africa" className="bg-[#0c0c0c] ring-1 ring-white/10"><Heading title="Africa" href="/news" />{layout.africa[0] ? <ArticleAnchor article={layout.africa[0]} className="group grid min-h-[168px] grid-cols-[38%_1fr]"><img src={layout.africa[0].thumbnail || FANS_IMAGE} alt="" className="h-full min-h-[168px] w-full object-cover" loading="lazy" /><div className="flex flex-col justify-center p-3"><h3 className="text-[15px] font-extrabold leading-tight group-hover:text-[#f5ca55]">{layout.africa[0].title}</h3><p className="mt-2 line-clamp-3 text-[11px] leading-4 text-white/55">{layout.africa[0].description}</p></div></ArticleAnchor> : <Link href="/news" className="grid min-h-[168px] grid-cols-[38%_1fr]"><img src={FANS_IMAGE} alt="" className="h-full min-h-[168px] w-full object-cover" /><div className="flex flex-col justify-center p-3"><h3 className="text-[15px] font-extrabold">African football belongs on the front page</h3><p className="mt-2 text-[11px] leading-4 text-white/55">CAF, national teams, players abroad and East Africa.</p></div></Link>}</section>
        <section id="fan-zone" className="bg-[#0c0c0c] ring-1 ring-white/10"><Heading title="Fan zone" href="/debates" action="Join debate" /><div className="p-4"><p className="text-[15px] font-extrabold leading-tight">{debates[0]?.title || "What is the biggest football argument in your group chat today?"}</p><div className="mt-4 grid grid-cols-2 gap-2">{debates[0] ? <><Link href="/debates" className="border border-white/12 px-3 py-2 text-[11px] text-white/75">{debates[0].left}</Link><Link href="/debates" className="border border-white/12 px-3 py-2 text-[11px] text-white/75">{debates[0].right}</Link></> : <><Link href="/debates" className="border border-white/12 px-3 py-2 text-[11px] text-white/75">Open debates</Link><Link href="/fan-zones" className="border border-white/12 px-3 py-2 text-[11px] text-white/75">Fan posts</Link></>}</div><p className="mt-4 text-[9px] uppercase tracking-[.14em] text-white/35">{debates[0] ? `${debates[0].totalVotes} community votes` : leaderboard[0] ? `${String(leaderboard[0].name)} leads` : "Kenyan football conversation"}</p></div></section>
        <section id="predictions" className="bg-[#0c0c0c] ring-1 ring-white/10"><Heading title="Predictions" href="/leaderboard" action="Leaderboard" /><div className="p-4"><p className="text-[9px] uppercase tracking-[.14em] text-white/40">Next match</p><h3 className="mt-1 text-[15px] font-extrabold">{liveLine ? `${short(liveLine.home)} vs ${short(liveLine.away)}` : "Make your football prediction"}</h3><p className="mt-1 text-[10px] text-white/45">{liveLine ? kickoff(liveLine) : "Fixtures, score calls and community picks"}</p><div className="mt-4 grid grid-cols-3 gap-1.5"><Link href="/predictions" className="bg-[#bf1721] px-2 py-2 text-center text-[9px] font-black uppercase">Home</Link><Link href="/predictions" className="bg-white/10 px-2 py-2 text-center text-[9px] font-black uppercase">Draw</Link><Link href="/predictions" className="bg-[#244b88] px-2 py-2 text-center text-[9px] font-black uppercase">Away</Link></div><p className="mt-3 text-[9px] text-[#f5ca55]">Community prediction / MTC points only</p></div></section>
        <section id="wire" className="bg-[#0c0c0c] ring-1 ring-white/10"><Heading title="The wire" href="/news" />{external.length ? <div className="divide-y divide-white/10 px-3">{external.slice(0,3).map((a) => <ArticleAnchor key={a.id || a.link} article={a} className="group grid grid-cols-[1fr_52px] gap-2 py-2.5"><div><p className="text-[8px] font-black uppercase tracking-[.12em] text-[#ef3038]">{a.source}</p><h3 className="mt-1 line-clamp-2 text-[11px] font-bold leading-[1.2] group-hover:text-[#f5ca55]">{a.title}</h3></div><img src={a.thumbnail || DEFAULT_IMAGE} alt="" className="h-10 w-[52px] object-cover" loading="lazy" /></ArticleAnchor>)}</div> : <div className="grid min-h-[168px] place-items-center px-5 text-center"><Link href="/videos" className="text-xs text-white/55 hover:text-white"><Newspaper className="mx-auto mb-2 h-5 w-5 text-[#ef3038]" />News and videos from the wider football world</Link></div>}</section>
      </section>
    </div>
    <footer className="mt-4 border-t border-white/15 bg-black"><div className="mx-auto max-w-[1500px] px-4 py-7"><div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-[1.35fr_repeat(4,1fr)]"><div><p className="font-serif text-3xl font-black">BALLMTAANI</p><p className="mt-3 max-w-[250px] text-[11px] leading-5 text-white/45">Kenya&apos;s football fan platform for news, analysis, live scores and community.</p></div><FooterColumn title="BallMtaani" links={[["About", "/about"], ["Editorial", "/news"], ["Contact", "/contact"]]} /><FooterColumn title="Match centre" links={[["Scores & fixtures", "/matches"], ["League tables", "/leagues"], ["Live centre", "/live-center"]]} /><FooterColumn title="Mtaa Play" links={[["Predictions", "/predictions"], ["Debates", "/debates"], ["Trivia", "/trivia"]]} /><FooterColumn title="Legal" links={[["Privacy", "/privacy"], ["Terms", "/terms"], ["Contact", "/contact"]]} /></div><div className="mt-7 flex flex-col gap-2 border-t border-white/10 pt-4 text-[9px] text-white/30 sm:flex-row sm:justify-between"><p>Copyright {new Date().getFullYear()} Ball Mtaani. Football. From where we stand.</p><p>MTC is not cash. Ball Mtaani is not gambling</p></div></div></footer>
  </main>;
}
