/**
 * BallMtaani Edge Phase 8 — B2B Prediction Widget Delivery Engine
 * Delivers embeddable prediction cards and fixture lists for publisher websites with domain allowlist verification.
 */

import { MatchPredictionOutput } from "../types";

export interface WidgetPayload {
  widgetType: "match_card" | "upcoming_list" | "performance_summary";
  theme: "light" | "dark";
  language: string;
  attribution: string;
  disclaimer: string;
  data: any;
}

export class WidgetDeliveryService {
  static validateDomain(requestOrigin: string, allowedOrigins: string[]): boolean {
    if (allowedOrigins.includes("*")) return true;
    return allowedOrigins.some((origin) => requestOrigin.toLowerCase().includes(origin.toLowerCase()));
  }

  static generateMatchCardWidget(
    prediction: MatchPredictionOutput,
    origin: string = "example.com",
    allowedOrigins: string[] = ["*"]
  ): WidgetPayload | { error: string } {
    if (!this.validateDomain(origin, allowedOrigins)) {
      return { error: `Domain '${origin}' is not authorized to embed BallMtaani Edge widgets.` };
    }

    return {
      widgetType: "match_card",
      theme: "dark",
      language: "en",
      attribution: "Powered by BallMtaani Edge Intelligence Engine",
      disclaimer: "Statistical probabilities generated by BallMtaani Edge. Outcomes remain uncertain. (18+)",
      data: {
        fixtureId: prediction.fixtureId,
        homeTeam: prediction.homeTeam,
        awayTeam: prediction.awayTeam,
        competition: prediction.competition,
        homeWinProb: prediction.homeWinProb,
        drawProb: prediction.drawProb,
        awayWinProb: prediction.awayWinProb,
        expectedHomeGoals: prediction.expectedHomeGoals,
        expectedAwayGoals: prediction.expectedAwayGoals,
        confidence: prediction.confidence,
        publishedAt: prediction.publishedAt,
      },
    };
  }
}
