create table if not exists public.war_room_daily (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day_key date not null,
  rumor_pick text null check (rumor_pick in ('true', 'cap')),
  lineup_pick text null,
  receipt_pick text null check (receipt_pick in ('true', 'cap')),
  completed_count int not null default 0,
  streak int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, day_key)
);

alter table public.war_room_daily enable row level security;

create policy if not exists "war_room_daily_select_own"
  on public.war_room_daily
  for select
  using (auth.uid() = user_id);

create policy if not exists "war_room_daily_insert_own"
  on public.war_room_daily
  for insert
  with check (auth.uid() = user_id);

create policy if not exists "war_room_daily_update_own"
  on public.war_room_daily
  for update
  using (auth.uid() = user_id);

create or replace function public.war_room_daily_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_war_room_daily_updated_at on public.war_room_daily;
create trigger trg_war_room_daily_updated_at
before update on public.war_room_daily
for each row execute function public.war_room_daily_set_updated_at();
